# Preprocessing train data

In [21]:
import numpy as np 
import pandas as pd

In [22]:
data = pd.read_csv("train.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 20 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int64
 2   elapsed_time    int64
 3   event_name      object
 4   name            object
 5   level           int64
 6   page            float64
 7   room_coor_x     float64
 8   room_coor_y     float64
 9   screen_coor_x   float64
 10  screen_coor_y   float64
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  fullscreen      float64
 17  hq              float64
 18  music           float64
 19  level_group     object
dtypes: float64(9), int64(4), object(7)
memory usage: 2.0+ GB

In [23]:
data

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,NaN,NaN,NaN,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174206,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,NaN,NaN,NaN,13-22
13174207,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,NaN,NaN,NaN,13-22
13174208,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,NaN,NaN,NaN,13-22
13174209,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,NaN,NaN,NaN,13-22
13174210,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,NaN,NaN,NaN,13-22

##### As we could see, memory usage is over 2 GB. Later we try to decrease this.

## 1. Have an Overview of data

In [24]:
data.describe(include='all')

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
count,1.317421e+07,1.317421e+07,1.317421e+07,13174211,13174211,1.317421e+07,284746.000000,1.213797e+07,1.213797e+07,1.213797e+07,1.213797e+07,1.000737e+06,4806891,9014563,13174211,4806945,0.0,0.0,0.0,13174211
unique,NaN,NaN,NaN,11,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594,127,19,126,NaN,NaN,NaN,3
top,NaN,NaN,NaN,navigate_click,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,undefined,worker,tunic.historicalsociety.entry,tunic.historicalsociety.cage.confrontation,NaN,NaN,NaN,13-22
freq,NaN,NaN,NaN,5687896,6377305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178294,939555,1816202,333363,NaN,NaN,NaN,6746397
mean,2.113413e+16,6.526426e+02,3.846817e+06,NaN,NaN,1.219194e+01,3.157930,-5.493615e+01,-1.162997e+02,4.581144e+02,3.852363e+02,3.186237e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5.665220e+14,6.275818e+02,2.701387e+07,NaN,NaN,6.499188e+00,2.064042,5.201468e+02,2.185912e+02,2.472144e+02,1.292879e+02,3.692265e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.009031e+16,0.000000e+00,0.000000e+00,NaN,NaN,0.000000e+00,0.000000,-1.992355e+03,-9.181587e+02,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.101031e+16,2.890000e+02,4.394300e+05,NaN,NaN,6.000000e+00,1.000000,-3.529376e+02,-2.128361e+02,2.690000e+02,3.040000e+02,1.000000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.104022e+16,5.960000e+02,1.013425e+06,NaN,NaN,1.300000e+01,3.000000,-1.116317e+01,-9.778151e+01,4.470000e+02,3.970000e+02,4.180000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.110051e+16,8.970000e+02,1.740050e+06,NaN,NaN,1.800000e+01,5.000000,2.963618e+02,2.268531e+01,6.630000e+02,4.710000e+02,1.266000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.210022e+16,2.047300e+04,1.749293e+09,NaN,NaN,2.200000e+01,6.000000,1.261774e+03,5.436164e+02,1.916000e+03,1.439000e+03,2.199078e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
print(data.head(50))

           session_id  index  elapsed_time          event_name       name  \
0   20090312431273200      0             0      cutscene_click      basic
1   20090312431273200      1          1323        person_click      basic
2   20090312431273200      2           831        person_click      basic
3   20090312431273200      3          1147        person_click      basic
4   20090312431273200      4          1863        person_click      basic
5   20090312431273200      5          3423        person_click      basic
6   20090312431273200      6          5197        person_click      basic
7   20090312431273200      7          6180        person_click      basic
8   20090312431273200      8          7014        person_click      basic
9   20090312431273200      9          7946        person_click      basic
10  20090312431273200     10          9133      navigate_click  undefined
11  20090312431273200     11         10263        person_click      basic
12  20090312431273200     12         12030      navigate_click  undefined
13  20090312431273200     13         13030   observation_click      basic
14  20090312431273200     14         14814      navigate_click  undefined
15  20090312431273200     15         15498      navigate_click  undefined
16  20090312431273200     16         16046      navigate_click  undefined
17  20090312431273200     17         17462      navigate_click  undefined
18  20090312431273200     18         18164      navigate_click  undefined
19  20090312431273200     19         18796      navigate_click  undefined
20  20090312431273200     20         19380      navigate_click  undefined
21  20090312431273200     21         20014      navigate_click  undefined
22  20090312431273200     22         20681      navigate_click  undefined
23  20090312431273200     23         21413      navigate_click  undefined
24  20090312431273200     24         22013      navigate_click  undefined
25  20090312431273200     25         22996      navigate_click  undefined
26  20090312431273200     26         24348  notification_click      basic
27  20090312431273200     27         25766        object_click      close
28  20090312431273200     28         28113      navigate_click  undefined
29  20090312431273200     29         32229  notification_click      basic
30  20090312431273200     30         33063  notification_click      basic
31  20090312431273200     31         34245  notification_click      basic
32  20090312431273200     32         36433        object_click      close
33  20090312431273200     33         36346      navigate_click  undefined
34  20090312431273200     34         36896      navigate_click  undefined
35  20090312431273200     35         37445      navigate_click  undefined
36  20090312431273200     36         39845      navigate_click  undefined
37  20090312431273200     37         41297   observation_click      basic
38  20090312431273200     38         41898      navigate_click  undefined
39  20090312431273200     39         43413      navigate_click  undefined
40  20090312431273200     40         44196      navigate_click  undefined
41  20090312431273200     41         45062      cutscene_click      basic
42  20090312431273200     42         46046      cutscene_click      basic
43  20090312431273200     43         47362      cutscene_click      basic
44  20090312431273200     44         48112      cutscene_click      basic
45  20090312431273200     45         49514      cutscene_click      basic
46  20090312431273200     46         50144      cutscene_click      basic
47  20090312431273200     47         50794      cutscene_click      basic
48  20090312431273200     48         52413      cutscene_click      basic
49  20090312431273200     49         52328        object_hover      basic

    level  page  room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  \
0       0   NaN  -413.991405  -159.314686          380.0          494.0
1       0   NaN  -413.991405  -159.314686          380.0          494.0
2       0   NaN  -413.991405  -159.314686          380.0          494.0
3       0   NaN  -413.991405  -159.314686          380.0          494.0
4       0   NaN  -412.991405  -159.314686          381.0          494.0
5       0   NaN  -412.991405  -157.314686          381.0          492.0
6       0   NaN   478.485079  -199.971679          593.0          485.0
7       0   NaN   503.355128  -168.619913          609.0          453.0
8       0   NaN   510.733442  -157.720642          615.0          442.0
9       0   NaN   512.048005  -153.743631          616.0          438.0
10      0   NaN   501.110035  -160.748164          605.0          445.0
11      0   NaN   501.084991  -164.762366          605.0          445.0
12      0   NaN   510.081490  -106.352093          614.0          386.0
13      0   NaN   486.877471   -98.538288          614.0          386.0
14      0   NaN   273.991410  -196.802371          406.0          486.0
15      0   NaN   185.708460  -205.806533          363.0          492.0
16      0   NaN     0.583565  -225.691296          234.0          510.0
17      0   NaN   350.344270  -173.948629          766.0          454.0
18      0   NaN   -37.961716  -255.711127          301.0          542.0
19      0   NaN  -133.236752  -251.376033          203.0          531.0
20      0   NaN  -253.401844  -253.023019          201.0          530.0
21      0   NaN  -385.096230  -253.134658          197.0          529.0
22      0   NaN  -564.055739  -216.507416          133.0          492.0
23      0   NaN  -720.325333  -207.429918           99.0          487.0
24      0   NaN  -818.128894  -194.244643           92.0          476.0
25      0   NaN  -924.692590  -254.280542           75.0          539.0
26      0   NaN  -472.142708  -117.942846          554.0          394.0
27      0   NaN  -206.471467   199.155280          822.0           76.0
28      1   NaN  -587.657879   -27.916913          441.0          303.0
29      1   NaN  -182.558163    -1.906501          767.0          305.0
30      1   NaN  -182.500704   -55.888296          767.0          359.0
31      1   NaN  -182.486523   -55.883804          767.0          359.0
32      1   NaN  -113.484832   241.116732          836.0           62.0
33      1   NaN  -453.484720  -193.883232          496.0          497.0
34      1   NaN  -381.244988   -22.454632          525.0          316.0
35      1   NaN  -358.832033    54.847822          462.0          249.0
36      1   NaN  -234.247817   -77.052212          245.0          376.0
37      1   NaN  -400.311667  -117.476454          179.0          405.0
38      1   NaN  -418.370598  -120.264333          172.0          407.0
39      1   NaN  -486.265977  -109.112818          151.0          399.0
40      1   NaN   385.587985  -135.776680          461.0          413.0
41      1   NaN    93.811703   -60.345450          338.0          368.0
42      1   NaN   133.978871   -85.715094          390.0          386.0
43      1   NaN   125.931445   -83.374177          390.0          385.0
44      1   NaN   123.708202   -80.064777          389.0          383.0
45      1   NaN   117.007942   -76.791509          385.0          381.0
46      1   NaN   116.997193   -76.790557          385.0          381.0
47      1   NaN   115.365405   -81.675345          384.0          384.0
48      1   NaN   113.735877   -84.931969          383.0          386.0
49      1   NaN          NaN          NaN            NaN            NaN

    hover_duration                                               text  \
0              NaN                                          undefined
1              NaN                      Whatcha doing over there, Jo?
2              NaN                             Just talking to Teddy.
3              NaN                         I gotta run to my meeting!
4              NaN                                Can I come, Gramps?
5              NaN  Sure thing, Jo. Grab your notebook and come up...
6              NaN                              See you later, Teddy.
7              NaN                   I get to go to Gramps's meeting!
8              NaN                   Now where did I put my notebook?
9              NaN                           \u00f0\u0178\u02dc\u00b4
10             NaN                                                NaN
11             NaN                           \u00f0\u0178\u02dc\u00b4
12             NaN                                                NaN
13             NaN               I love these photos of me and Teddy!
14             NaN                                                NaN
15             NaN                                                NaN
16             NaN                                                NaN
17             NaN                                                NaN
18             NaN                                                NaN
19             NaN                                                NaN
20             NaN                                                NaN
21             NaN                                                NaN
22             NaN                                                NaN
23             NaN                                                NaN
24             NaN                                                NaN
25             NaN                                                NaN
26             NaN                                          Found it!
27             NaN                                                NaN
28             NaN                                                NaN
29             NaN            Gramps is in trouble for losing papers?
30             NaN                               This can't be right!
31             NaN                       Gramps is a great historian!
32             NaN                                                NaN
33             NaN                                                NaN
34             NaN                                                NaN
35             NaN                                                NaN
36             NaN                                                NaN
37             NaN                   Hmm. Button's still not working.
38             NaN                                                NaN
39             NaN                                                NaN
40             NaN                                                NaN
41             NaN  Let's get started. The Wisconsin Wonders exhib...
42             NaN       Who wants to investigate the shirt artifact?
43             NaN  Not Leopold here. He's been losing papers lately.
44             NaN                                               Hey!
45             NaN      It's true, they do keep going missing lately.
46             NaN                                               See?
47             NaN          Besides, I already figured out the shirt.
48             NaN                  It's a women's basketball jersey!
49          7899.0                                                NaN

                 fqid                         room_fqid  \
0               intro    tunic.historicalsociety.closet
1              gramps    tunic.historicalsociety.closet
2              gramps    tunic.historicalsociety.closet
3              gramps    tunic.historicalsociety.closet
4              gramps    tunic.historicalsociety.closet
5              gramps    tunic.historicalsociety.closet
6               teddy    tunic.historicalsociety.closet
7               teddy    tunic.historicalsociety.closet
8               teddy    tunic.historicalsociety.closet
9               teddy    tunic.historicalsociety.closet
10              teddy    tunic.historicalsociety.closet
11              teddy    tunic.historicalsociety.closet
12              photo    tunic.historicalsociety.closet
13              photo    tunic.historicalsociety.closet
14                NaN    tunic.historicalsociety.closet
15                NaN    tunic.historicalsociety.closet
16                NaN    tunic.historicalsociety.closet
17                NaN    tunic.historicalsociety.closet
18                NaN    tunic.historicalsociety.closet
19                NaN    tunic.historicalsociety.closet
20                NaN    tunic.historicalsociety.closet
21                NaN    tunic.historicalsociety.closet
22                NaN    tunic.historicalsociety.closet
23                NaN    tunic.historicalsociety.closet
24                NaN    tunic.historicalsociety.closet
25           notebook    tunic.historicalsociety.closet
26                NaN    tunic.historicalsociety.closet
27           notebook    tunic.historicalsociety.closet
28  retirement_letter    tunic.historicalsociety.closet
29                NaN    tunic.historicalsociety.closet
30                NaN    tunic.historicalsociety.closet
31                NaN    tunic.historicalsociety.closet
32  retirement_letter    tunic.historicalsociety.closet
33                NaN    tunic.historicalsociety.closet
34                NaN    tunic.historicalsociety.closet
35         tobasement    tunic.historicalsociety.closet
36            janitor  tunic.historicalsociety.basement
37            janitor  tunic.historicalsociety.basement
38                NaN  tunic.historicalsociety.basement
39            toentry  tunic.historicalsociety.basement
40         groupconvo     tunic.historicalsociety.entry
41         groupconvo     tunic.historicalsociety.entry
42         groupconvo     tunic.historicalsociety.entry
43         groupconvo     tunic.historicalsociety.entry
44         groupconvo     tunic.historicalsociety.entry
45         groupconvo     tunic.historicalsociety.entry
46         groupconvo     tunic.historicalsociety.entry
47         groupconvo     tunic.historicalsociety.entry
48         groupconvo     tunic.historicalsociety.entry
49         groupconvo     tunic.historicalsociety.entry

                                            text_fqid  fullscreen  hq  music  \
0                tunic.historicalsociety.closet.intro         NaN NaN    NaN
1   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
2   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
3   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
4   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
5   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
6   tunic.historicalsociety.closet.teddy.intro_0_cs_0         NaN NaN    NaN
7   tunic.historicalsociety.closet.teddy.intro_0_cs_0         NaN NaN    NaN
8   tunic.historicalsociety.closet.teddy.intro_0_cs_0         NaN NaN    NaN
9   tunic.historicalsociety.closet.teddy.intro_0_cs_0         NaN NaN    NaN
10                                                NaN         NaN NaN    NaN
11  tunic.historicalsociety.closet.teddy.intro_0_cs_5         NaN NaN    NaN
12                                                NaN         NaN NaN    NaN
13               tunic.historicalsociety.closet.photo         NaN NaN    NaN
14                                                NaN         NaN NaN    NaN
15                                                NaN         NaN NaN    NaN
16                                                NaN         NaN NaN    NaN
17                                                NaN         NaN NaN    NaN
18                                                NaN         NaN NaN    NaN
19                                                NaN         NaN NaN    NaN
20                                                NaN         NaN NaN    NaN
21                                                NaN         NaN NaN    NaN
22                                                NaN         NaN NaN    NaN
23                                                NaN         NaN NaN    NaN
24                                                NaN         NaN NaN    NaN
25                                                NaN         NaN NaN    NaN
26            tunic.historicalsociety.closet.notebook         NaN NaN    NaN
27                                                NaN         NaN NaN    NaN
28                                                NaN         NaN NaN    NaN
29  tunic.historicalsociety.closet.retirement_lett...         NaN NaN    NaN
30  tunic.historicalsociety.closet.retirement_lett...         NaN NaN    NaN
31  tunic.historicalsociety.closet.retirement_lett...         NaN NaN    NaN
32                                                NaN         NaN NaN    NaN
33                                                NaN         NaN NaN    NaN
34                                                NaN         NaN NaN    NaN
35                                                NaN         NaN NaN    NaN
36                                                NaN         NaN NaN    NaN
37           tunic.historicalsociety.basement.janitor         NaN NaN    NaN
38                                                NaN         NaN NaN    NaN
39                                                NaN         NaN NaN    NaN
40                                                NaN         NaN NaN    NaN
41           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
42           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
43           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
44           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
45           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
46           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
47           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
48           tunic.historicalsociety.entry.groupconvo         NaN NaN    NaN
49                                                NaN         NaN NaN    NaN

   level_group
0          0-4
1          0-4
2          0-4
3          0-4
4          0-4
5          0-4
6          0-4
7          0-4
8          0-4
9          0-4
10         0-4
11         0-4
12         0-4
13         0-4
14         0-4
15         0-4
16         0-4
17         0-4
18         0-4
19         0-4
20         0-4
21         0-4
22         0-4
23         0-4
24         0-4
25         0-4
26         0-4
27         0-4
28         0-4
29         0-4
30         0-4
31         0-4
32         0-4
33         0-4
34         0-4
35         0-4
36         0-4
37         0-4
38         0-4
39         0-4
40         0-4
41         0-4
42         0-4
43         0-4
44         0-4
45         0-4
46         0-4
47         0-4
48         0-4
49         0-4

## 2. Wipe out NA values

##### Here we could see three columns all filled with NaN values. Drop them

In [26]:
## drop those columns as NA
data = data.drop(['music','hq','fullscreen'], axis=1)
print(data.head(50))

           session_id  index  elapsed_time          event_name       name  \
0   20090312431273200      0             0      cutscene_click      basic
1   20090312431273200      1          1323        person_click      basic
2   20090312431273200      2           831        person_click      basic
3   20090312431273200      3          1147        person_click      basic
4   20090312431273200      4          1863        person_click      basic
5   20090312431273200      5          3423        person_click      basic
6   20090312431273200      6          5197        person_click      basic
7   20090312431273200      7          6180        person_click      basic
8   20090312431273200      8          7014        person_click      basic
9   20090312431273200      9          7946        person_click      basic
10  20090312431273200     10          9133      navigate_click  undefined
11  20090312431273200     11         10263        person_click      basic
12  20090312431273200     12         12030      navigate_click  undefined
13  20090312431273200     13         13030   observation_click      basic
14  20090312431273200     14         14814      navigate_click  undefined
15  20090312431273200     15         15498      navigate_click  undefined
16  20090312431273200     16         16046      navigate_click  undefined
17  20090312431273200     17         17462      navigate_click  undefined
18  20090312431273200     18         18164      navigate_click  undefined
19  20090312431273200     19         18796      navigate_click  undefined
20  20090312431273200     20         19380      navigate_click  undefined
21  20090312431273200     21         20014      navigate_click  undefined
22  20090312431273200     22         20681      navigate_click  undefined
23  20090312431273200     23         21413      navigate_click  undefined
24  20090312431273200     24         22013      navigate_click  undefined
25  20090312431273200     25         22996      navigate_click  undefined
26  20090312431273200     26         24348  notification_click      basic
27  20090312431273200     27         25766        object_click      close
28  20090312431273200     28         28113      navigate_click  undefined
29  20090312431273200     29         32229  notification_click      basic
30  20090312431273200     30         33063  notification_click      basic
31  20090312431273200     31         34245  notification_click      basic
32  20090312431273200     32         36433        object_click      close
33  20090312431273200     33         36346      navigate_click  undefined
34  20090312431273200     34         36896      navigate_click  undefined
35  20090312431273200     35         37445      navigate_click  undefined
36  20090312431273200     36         39845      navigate_click  undefined
37  20090312431273200     37         41297   observation_click      basic
38  20090312431273200     38         41898      navigate_click  undefined
39  20090312431273200     39         43413      navigate_click  undefined
40  20090312431273200     40         44196      navigate_click  undefined
41  20090312431273200     41         45062      cutscene_click      basic
42  20090312431273200     42         46046      cutscene_click      basic
43  20090312431273200     43         47362      cutscene_click      basic
44  20090312431273200     44         48112      cutscene_click      basic
45  20090312431273200     45         49514      cutscene_click      basic
46  20090312431273200     46         50144      cutscene_click      basic
47  20090312431273200     47         50794      cutscene_click      basic
48  20090312431273200     48         52413      cutscene_click      basic
49  20090312431273200     49         52328        object_hover      basic

    level  page  room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  \
0       0   NaN  -413.991405  -159.314686          380.0          494.0
1       0   NaN  -413.991405  -159.314686          380.0          494.0
2       0   NaN  -413.991405  -159.314686          380.0          494.0
3       0   NaN  -413.991405  -159.314686          380.0          494.0
4       0   NaN  -412.991405  -159.314686          381.0          494.0
5       0   NaN  -412.991405  -157.314686          381.0          492.0
6       0   NaN   478.485079  -199.971679          593.0          485.0
7       0   NaN   503.355128  -168.619913          609.0          453.0
8       0   NaN   510.733442  -157.720642          615.0          442.0
9       0   NaN   512.048005  -153.743631          616.0          438.0
10      0   NaN   501.110035  -160.748164          605.0          445.0
11      0   NaN   501.084991  -164.762366          605.0          445.0
12      0   NaN   510.081490  -106.352093          614.0          386.0
13      0   NaN   486.877471   -98.538288          614.0          386.0
14      0   NaN   273.991410  -196.802371          406.0          486.0
15      0   NaN   185.708460  -205.806533          363.0          492.0
16      0   NaN     0.583565  -225.691296          234.0          510.0
17      0   NaN   350.344270  -173.948629          766.0          454.0
18      0   NaN   -37.961716  -255.711127          301.0          542.0
19      0   NaN  -133.236752  -251.376033          203.0          531.0
20      0   NaN  -253.401844  -253.023019          201.0          530.0
21      0   NaN  -385.096230  -253.134658          197.0          529.0
22      0   NaN  -564.055739  -216.507416          133.0          492.0
23      0   NaN  -720.325333  -207.429918           99.0          487.0
24      0   NaN  -818.128894  -194.244643           92.0          476.0
25      0   NaN  -924.692590  -254.280542           75.0          539.0
26      0   NaN  -472.142708  -117.942846          554.0          394.0
27      0   NaN  -206.471467   199.155280          822.0           76.0
28      1   NaN  -587.657879   -27.916913          441.0          303.0
29      1   NaN  -182.558163    -1.906501          767.0          305.0
30      1   NaN  -182.500704   -55.888296          767.0          359.0
31      1   NaN  -182.486523   -55.883804          767.0          359.0
32      1   NaN  -113.484832   241.116732          836.0           62.0
33      1   NaN  -453.484720  -193.883232          496.0          497.0
34      1   NaN  -381.244988   -22.454632          525.0          316.0
35      1   NaN  -358.832033    54.847822          462.0          249.0
36      1   NaN  -234.247817   -77.052212          245.0          376.0
37      1   NaN  -400.311667  -117.476454          179.0          405.0
38      1   NaN  -418.370598  -120.264333          172.0          407.0
39      1   NaN  -486.265977  -109.112818          151.0          399.0
40      1   NaN   385.587985  -135.776680          461.0          413.0
41      1   NaN    93.811703   -60.345450          338.0          368.0
42      1   NaN   133.978871   -85.715094          390.0          386.0
43      1   NaN   125.931445   -83.374177          390.0          385.0
44      1   NaN   123.708202   -80.064777          389.0          383.0
45      1   NaN   117.007942   -76.791509          385.0          381.0
46      1   NaN   116.997193   -76.790557          385.0          381.0
47      1   NaN   115.365405   -81.675345          384.0          384.0
48      1   NaN   113.735877   -84.931969          383.0          386.0
49      1   NaN          NaN          NaN            NaN            NaN

    hover_duration                                               text  \
0              NaN                                          undefined
1              NaN                      Whatcha doing over there, Jo?
2              NaN                             Just talking to Teddy.
3              NaN                         I gotta run to my meeting!
4              NaN                                Can I come, Gramps?
5              NaN  Sure thing, Jo. Grab your notebook and come up...
6              NaN                              See you later, Teddy.
7              NaN                   I get to go to Gramps's meeting!
8              NaN                   Now where did I put my notebook?
9              NaN                           \u00f0\u0178\u02dc\u00b4
10             NaN                                                NaN
11             NaN                           \u00f0\u0178\u02dc\u00b4
12             NaN                                                NaN
13             NaN               I love these photos of me and Teddy!
14             NaN                                                NaN
15             NaN                                                NaN
16             NaN                                                NaN
17             NaN                                                NaN
18             NaN                                                NaN
19             NaN                                                NaN
20             NaN                                                NaN
21             NaN                                                NaN
22             NaN                                                NaN
23             NaN                                                NaN
24             NaN                                                NaN
25             NaN                                                NaN
26             NaN                                          Found it!
27             NaN                                                NaN
28             NaN                                                NaN
29             NaN            Gramps is in trouble for losing papers?
30             NaN                               This can't be right!
31             NaN                       Gramps is a great historian!
32             NaN                                                NaN
33             NaN                                                NaN
34             NaN                                                NaN
35             NaN                                                NaN
36             NaN                                                NaN
37             NaN                   Hmm. Button's still not working.
38             NaN                                                NaN
39             NaN                                                NaN
40             NaN                                                NaN
41             NaN  Let's get started. The Wisconsin Wonders exhib...
42             NaN       Who wants to investigate the shirt artifact?
43             NaN  Not Leopold here. He's been losing papers lately.
44             NaN                                               Hey!
45             NaN      It's true, they do keep going missing lately.
46             NaN                                               See?
47             NaN          Besides, I already figured out the shirt.
48             NaN                  It's a women's basketball jersey!
49          7899.0                                                NaN

                 fqid                         room_fqid  \
0               intro    tunic.historicalsociety.closet
1              gramps    tunic.historicalsociety.closet
2              gramps    tunic.historicalsociety.closet
3              gramps    tunic.historicalsociety.closet
4              gramps    tunic.historicalsociety.closet
5              gramps    tunic.historicalsociety.closet
6               teddy    tunic.historicalsociety.closet
7               teddy    tunic.historicalsociety.closet
8               teddy    tunic.historicalsociety.closet
9               teddy    tunic.historicalsociety.closet
10              teddy    tunic.historicalsociety.closet
11              teddy    tunic.historicalsociety.closet
12              photo    tunic.historicalsociety.closet
13              photo    tunic.historicalsociety.closet
14                NaN    tunic.historicalsociety.closet
15                NaN    tunic.historicalsociety.closet
16                NaN    tunic.historicalsociety.closet
17                NaN    tunic.historicalsociety.closet
18                NaN    tunic.historicalsociety.closet
19                NaN    tunic.historicalsociety.closet
20                NaN    tunic.historicalsociety.closet
21                NaN    tunic.historicalsociety.closet
22                NaN    tunic.historicalsociety.closet
23                NaN    tunic.historicalsociety.closet
24                NaN    tunic.historicalsociety.closet
25           notebook    tunic.historicalsociety.closet
26                NaN    tunic.historicalsociety.closet
27           notebook    tunic.historicalsociety.closet
28  retirement_letter    tunic.historicalsociety.closet
29                NaN    tunic.historicalsociety.closet
30                NaN    tunic.historicalsociety.closet
31                NaN    tunic.historicalsociety.closet
32  retirement_letter    tunic.historicalsociety.closet
33                NaN    tunic.historicalsociety.closet
34                NaN    tunic.historicalsociety.closet
35         tobasement    tunic.historicalsociety.closet
36            janitor  tunic.historicalsociety.basement
37            janitor  tunic.historicalsociety.basement
38                NaN  tunic.historicalsociety.basement
39            toentry  tunic.historicalsociety.basement
40         groupconvo     tunic.historicalsociety.entry
41         groupconvo     tunic.historicalsociety.entry
42         groupconvo     tunic.historicalsociety.entry
43         groupconvo     tunic.historicalsociety.entry
44         groupconvo     tunic.historicalsociety.entry
45         groupconvo     tunic.historicalsociety.entry
46         groupconvo     tunic.historicalsociety.entry
47         groupconvo     tunic.historicalsociety.entry
48         groupconvo     tunic.historicalsociety.entry
49         groupconvo     tunic.historicalsociety.entry

                                            text_fqid level_group
0                tunic.historicalsociety.closet.intro         0-4
1   tunic.historicalsociety.closet.gramps.intro_0_...         0-4
2   tunic.historicalsociety.closet.gramps.intro_0_...         0-4
3   tunic.historicalsociety.closet.gramps.intro_0_...         0-4
4   tunic.historicalsociety.closet.gramps.intro_0_...         0-4
5   tunic.historicalsociety.closet.gramps.intro_0_...         0-4
6   tunic.historicalsociety.closet.teddy.intro_0_cs_0         0-4
7   tunic.historicalsociety.closet.teddy.intro_0_cs_0         0-4
8   tunic.historicalsociety.closet.teddy.intro_0_cs_0         0-4
9   tunic.historicalsociety.closet.teddy.intro_0_cs_0         0-4
10                                                NaN         0-4
11  tunic.historicalsociety.closet.teddy.intro_0_cs_5         0-4
12                                                NaN         0-4
13               tunic.historicalsociety.closet.photo         0-4
14                                                NaN         0-4
15                                                NaN         0-4
16                                                NaN         0-4
17                                                NaN         0-4
18                                                NaN         0-4
19                                                NaN         0-4
20                                                NaN         0-4
21                                                NaN         0-4
22                                                NaN         0-4
23                                                NaN         0-4
24                                                NaN         0-4
25                                                NaN         0-4
26            tunic.historicalsociety.closet.notebook         0-4
27                                                NaN         0-4
28                                                NaN         0-4
29  tunic.historicalsociety.closet.retirement_lett...         0-4
30  tunic.historicalsociety.closet.retirement_lett...         0-4
31  tunic.historicalsociety.closet.retirement_lett...         0-4
32                                                NaN         0-4
33                                                NaN         0-4
34                                                NaN         0-4
35                                                NaN         0-4
36                                                NaN         0-4
37           tunic.historicalsociety.basement.janitor         0-4
38                                                NaN         0-4
39                                                NaN         0-4
40                                                NaN         0-4
41           tunic.historicalsociety.entry.groupconvo         0-4
42           tunic.historicalsociety.entry.groupconvo         0-4
43           tunic.historicalsociety.entry.groupconvo         0-4
44           tunic.historicalsociety.entry.groupconvo         0-4
45           tunic.historicalsociety.entry.groupconvo         0-4
46           tunic.historicalsociety.entry.groupconvo         0-4
47           tunic.historicalsociety.entry.groupconvo         0-4
48           tunic.historicalsociety.entry.groupconvo         0-4
49                                                NaN         0-4

## 3 Change Data type to save memory space

In [27]:
data['elapsed_time'] = data['elapsed_time'].astype(np.uint32)
data['level'] = data['level'].astype(np.uint8)
data['room_coor_x'] = data['room_coor_x'].astype(np.float32)
data['room_coor_y'] = data['room_coor_y'].astype(np.float32)
data['screen_coor_x'] = data['screen_coor_x'].astype(np.float32)
data['screen_coor_y'] = data['screen_coor_y'].astype(np.float32)
data['hover_duration'] = data['hover_duration'].astype(np.float32)


columns_to_convert = ['session_id','event_name','name','text','fqid','room_fqid','text_fqid','level_group']

for column in columns_to_convert:
    data[column] = data[column].astype('category')
    
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 17 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      category
 1   index           int64
 2   elapsed_time    uint32
 3   event_name      category
 4   name            category
 5   level           uint8
 6   page            float64
 7   room_coor_x     float32
 8   room_coor_y     float32
 9   screen_coor_x   float32
 10  screen_coor_y   float32
 11  hover_duration  float32
 12  text            category
 13  fqid            category
 14  room_fqid       category
 15  text_fqid       category
 16  level_group     category
dtypes: category(8), float32(5), float64(1), int64(1), uint32(1), uint8(1)
memory usage: 653.7 MB

##### Great! Now we reduced 2.3 GB to 565 MB, saved around 77% memory space!
##### However, the results of answer (which we need to predict is in another file), we combine it now

## 4. Combine Predictor Data

### 4.1 Preprocess Predictor Data

In [28]:
# import response data
predictorData = pd.read_csv("train_labels.csv")
predictorData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212022 entries, 0 to 212021
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   session_id  212022 non-null  object
 1   correct     212022 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.2+ MB

In [29]:
predictorData.describe(include='all')

                  session_id        correct
count                 212022  212022.000000
unique                212022            NaN
top     20090312431273200_q1            NaN
freq                       1            NaN
mean                     NaN       0.703946
std                      NaN       0.456516
min                      NaN       0.000000
25%                      NaN       0.000000
50%                      NaN       1.000000
75%                      NaN       1.000000
max                      NaN       1.000000

In [30]:
print(predictorData.head(100))

              session_id  correct
0   20090312431273200_q1        1
1   20090312433251036_q1        0
2   20090314121766812_q1        1
3   20090314363702160_q1        1
4   20090314441803444_q1        1
..                   ...      ...
95  20100111290365256_q1        0
96  20100111293440890_q1        1
97  20100111315145150_q1        1
98  20100111354105336_q1        1
99  20100111374821010_q1        1

[100 rows x 2 columns]

##### As we see, we can't simply combine it as not well being preprocessed. 
##### We extract useful information now

In [31]:
# 1. split the "session_id" column into "sessionID" and "qns"
split_predictorData = predictorData['session_id'].str.split("_", expand=True)
# rename the headers
split_predictorData = split_predictorData.rename(columns={split_predictorData.columns[0]: 'sessionID', split_predictorData.columns[1]: 'qns'})
# combine the dataframe of the 2 split items and the correct column of the original dataframe
processed_predictorData = pd.concat([split_predictorData, predictorData['correct']], axis=1)
#change datatype for 'correct' column from int64 to object (CONSIDER 'BOOL' INSTEAD)
processed_predictorData['correct'] = processed_predictorData['correct'].astype('object')

# 2. split the "qns" column into "q" and "question id"
split_qns = processed_predictorData['qns'].str.split("q", expand=True)
split_qns = split_qns.rename(columns={split_qns.columns[0]: 'q', split_qns.columns[1]: 'qns'})
# combine the dataframe of the 'qns' into processed_predictorData
processed_predictorData_sortedBySessionID = pd.concat([processed_predictorData['sessionID'], split_qns['qns'], processed_predictorData['correct']], axis=1)
# convert the datatype of qns to integer for sorting
processed_predictorData_sortedBySessionID['qns'] = processed_predictorData_sortedBySessionID['qns'].astype('int')
# sort the dataset according to ascending order of the 'sessionID' and 'qns'
processed_predictorData_sortedBySessionID = processed_predictorData_sortedBySessionID.sort_values(['sessionID', 'qns'], ascending=[True, True])
# reset the index
processed_predictorData_sortedBySessionID = processed_predictorData_sortedBySessionID.reset_index(drop=True)
processed_predictorData_sortedBySessionID.info()

# 3. Have a overview of data
print(processed_predictorData_sortedBySessionID.head(50))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212022 entries, 0 to 212021
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   sessionID  212022 non-null  object
 1   qns        212022 non-null  int64
 2   correct    212022 non-null  object
dtypes: int64(1), object(2)
memory usage: 4.9+ MB
            sessionID  qns correct
0   20090312431273200    1       1
1   20090312431273200    2       1
2   20090312431273200    3       1
3   20090312431273200    4       1
4   20090312431273200    5       1
5   20090312431273200    6       1
6   20090312431273200    7       1
7   20090312431273200    8       1
8   20090312431273200    9       1
9   20090312431273200   10       1
10  20090312431273200   11       1
11  20090312431273200   12       1
12  20090312431273200   13       0
13  20090312431273200   14       1
14  20090312431273200   15       1
15  20090312431273200   16       0
16  20090312431273200   17       1
17  20090312431273200   18       1
18  20090312433251036    1       0
19  20090312433251036    2       1
20  20090312433251036    3       1
21  20090312433251036    4       1
22  20090312433251036    5       0
23  20090312433251036    6       1
24  20090312433251036    7       1
25  20090312433251036    8       0
26  20090312433251036    9       1
27  20090312433251036   10       0
28  20090312433251036   11       0
29  20090312433251036   12       1
30  20090312433251036   13       0
31  20090312433251036   14       1
32  20090312433251036   15       0
33  20090312433251036   16       1
34  20090312433251036   17       0
35  20090312433251036   18       1
36  20090314121766812    1       1
37  20090314121766812    2       1
38  20090314121766812    3       1
39  20090314121766812    4       0
40  20090314121766812    5       0
41  20090314121766812    6       1
42  20090314121766812    7       1
43  20090314121766812    8       0
44  20090314121766812    9       0
45  20090314121766812   10       1
46  20090314121766812   11       1
47  20090314121766812   12       1
48  20090314121766812   13       0
49  20090314121766812   14       1

### 4.2 Combine with train data by splitting into 3 sections

#### To further reduce data set and implement data science skills we learned, we extract one characteristic value for each column and merge it with the results dataframe for future prediction.

##### We train one model for each of 18 questions. Furthermore, we use data from level_groups = '0-4' to train model for questions 1-3, and level groups '5-12' to train questions 4 thru 13 and level groups '13-22' to train questions 14 thru 18. Because this is the data we get (to predict corresponding questions) from Kaggle's inference API during test inference. We can improve our model by saving a user's previous data from earlier level_groups and using that to predict future level_groups

##### First we calculate the mean accuracy of answers of each three session

In [32]:
sub1 = processed_predictorData_sortedBySessionID[processed_predictorData_sortedBySessionID['qns']<4]
sub1 = sub1.groupby(['sessionID'])['correct'].mean().reset_index()

sub2 = processed_predictorData_sortedBySessionID[processed_predictorData_sortedBySessionID['qns']>=4]
sub2 = sub2[sub2['qns']<14]
sub2 = sub2.groupby(['sessionID'])['correct'].mean().reset_index()

sub3 = processed_predictorData_sortedBySessionID[processed_predictorData_sortedBySessionID['qns']>=14]
sub3 = sub1.groupby(['sessionID'])['correct'].mean().reset_index()

display(sub1,sub2,sub3)

               sessionID   correct
0      20090312431273200  1.000000
1      20090312433251036  0.666667
2      20090314121766812  1.000000
3      20090314363702160  1.000000
4      20090314441803444  1.000000
...                  ...       ...
11774  22100215342220508  1.000000
11775  22100215460321130  0.666667
11776  22100217104993650  1.000000
11777  22100219442786200  0.666667
11778  22100221145014656  0.333333

[11779 rows x 2 columns]

               sessionID  correct
0      20090312431273200      0.9
1      20090312433251036      0.5
2      20090314121766812      0.5
3      20090314363702160      0.9
4      20090314441803444      0.6
...                  ...      ...
11774  22100215342220508      0.8
11775  22100215460321130      0.6
11776  22100217104993650      0.9
11777  22100219442786200      0.7
11778  22100221145014656      0.4

[11779 rows x 2 columns]

               sessionID   correct
0      20090312431273200  1.000000
1      20090312433251036  0.666667
2      20090314121766812  1.000000
3      20090314363702160  1.000000
4      20090314441803444  1.000000
...                  ...       ...
11774  22100215342220508  1.000000
11775  22100215460321130  0.666667
11776  22100217104993650  1.000000
11777  22100219442786200  0.666667
11778  22100221145014656  0.333333

[11779 rows x 2 columns]

In [33]:
test = data.sort_values(['session_id', 'level_group'], ascending=[True, True])
test

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991394,-159.314682,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13173446,22100221145014656,795,3664936,navigate_click,undefined,12,NaN,939.575623,92.873199,805.0,268.0,NaN,NaN,tomap,tunic.historicalsociety.entry,NaN,5-12
13173447,22100221145014656,796,3665912,map_hover,basic,12,NaN,NaN,NaN,NaN,NaN,600.0,NaN,tomap,tunic.historicalsociety.entry,NaN,5-12
13173448,22100221145014656,797,3666188,map_click,undefined,12,NaN,486.913300,50.747986,465.0,298.0,NaN,NaN,tunic.capitol_1,tunic.historicalsociety.entry,NaN,5-12
13173449,22100221145014656,798,3667021,navigate_click,undefined,12,NaN,210.553955,-140.571701,395.0,390.0,NaN,NaN,chap2_finale_c,tunic.capitol_1.hall,NaN,5-12
13173450,22100221145014656,799,3668994,checkpoint,basic,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap2_finale_c,tunic.capitol_1.hall,NaN,5-12

##### Section 1

In [34]:
data1 = test[test['level_group'] == '0-4']
data1

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991394,-159.314682,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991394,-159.314682,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13172870,22100221145014656,206,352635,navigate_click,undefined,4,NaN,-914.204224,-50.000000,26.0,380.0,NaN,NaN,toentry,tunic.kohlcenter.halloffame,NaN,0-4
13172871,22100221145014656,207,353336,map_hover,basic,4,NaN,NaN,NaN,NaN,NaN,84.0,NaN,tunic.kohlcenter,tunic.kohlcenter.halloffame,NaN,0-4
13172872,22100221145014656,208,354020,map_click,undefined,4,NaN,-549.217712,-2.000000,449.0,332.0,NaN,NaN,tunic.capitol_0,tunic.kohlcenter.halloffame,NaN,0-4
13172873,22100221145014656,209,356238,navigate_click,undefined,4,NaN,313.584259,107.913147,463.0,226.0,NaN,NaN,chap1_finale,tunic.capitol_0.hall,NaN,0-4
13172874,22100221145014656,210,435055,checkpoint,basic,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap1_finale_c,tunic.capitol_0.hall,NaN,0-4

## How do we extract each characteristic value for each column?

### 1. Elapsed_time -> (total) elasped_time: The last value of each participant, which is the total time of elapsed time.
### 2. Event_name && Name -> Most click type: After deleting the most common navigate_click(click to proceed moving forward in game), we retain select the most click type (map, object, notebook, person)
### 3. Level -> deletion. As it only indicates which stage of game.
### 4. Page -> (bool) this value represents whether player clicked notebook or not. (Notebook is important for clue collection)
### 5. "room_coor_x	room_coor_y	screen_coor_x	screen_coor_y" -> Fullscreen. Although fullscreen is NaN and thus deleted previously, by evaluating those four parameters, we can derive whether it's fullscreen or not.
### 6. Hover_duration-> (mean) hover_duration. It reflects how long does the play pause the mouse.
### 7. "text	 fqid	room_fqid	text_fqid"-> deletion. As it's just the responses from game NPCs.
### 8. "level_group correct" : retain

In [82]:
# factor 1
total_elapsed_time = data1.groupby(['session_id'])['elapsed_time'].tail(1).reset_index()

# factor 2
filtered_data = data1[(data1['event_name'] != 'navigate_click') & (data1['event_name'] != 'cutscene_click')]
mode_event_name = filtered_data.groupby(['session_id'])['event_name'].apply(lambda x: x.mode()[0]).reset_index()

# factor 3
avg_page = data1.groupby(['session_id'])['page'].max().notnull().astype(int).reset_index()
avg_page = avg_page.rename(columns={'page': 'avg_page'})

# factor 4

# Find the maximum values of room_coor_x, screen_coor_x, room_coor_y, and screen_coor_y for each unique session_id
max_values = data1.groupby('session_id')[['room_coor_x', 'screen_coor_x', 'room_coor_y', 'screen_coor_y']].max()

# Create a new column named 'fullscreen' in the max_values dataframe that checks if the maximum room_coor_x is equal to the maximum screen_coor_x
max_values['fullscreen'] = (max_values['room_coor_x'] > 880) | (max_values['room_coor_y'] > 660)

# Create a new dataframe named 'fullscreen_df' that only contains the session_id and fullscreen columns from the max_values dataframe
fullscreen_df = max_values['fullscreen'].astype(int).reset_index()

# Merge the 'fullscreen' column with the unique 'session_id' column using an outer join on the 'session_id' column
unique_session_ids = data1['session_id'].unique()
unique_session_ids_df = pd.DataFrame({'session_id': unique_session_ids})
unique_session_ids_fullscreen = pd.merge(unique_session_ids_df, fullscreen_df, on='session_id', how='outer')

# Rename the 'fullscreen' column to 'fullscreen_flag'
unique_session_ids_fullscreen = unique_session_ids_fullscreen.rename(columns={'fullscreen': 'fullscreen_flag'})



# factor 5
avg_hover_duration = data1.groupby(['session_id'])['hover_duration'].mean().reset_index()

# Merge
temp_level_group = pd.DataFrame({'level_group': ['0-4'] * 11779})
part1 = pd.concat([avg_hover_duration['session_id'], 
                   total_elapsed_time['elapsed_time'], 
                   mode_event_name['event_name'], avg_page['avg_page'],
                     unique_session_ids_fullscreen['fullscreen_flag'],
                       avg_hover_duration['hover_duration'], 
                         temp_level_group['level_group'], sub1['correct']]
                          , axis = 1)


part1.head(60)

,session_id,elapsed_time,event_name,avg_page,fullscreen_flag,hover_duration,level_group,correct
0,20090312431273200,194860,person_click,0,1,2389.500000,0-4,1.000000
1,20090312433251036,233752,person_click,1,1,1378.750000,0-4,0.666667
2,20090314121766812,393360,object_click,1,1,1603.400024,0-4,1.000000
3,20090314363702160,217574,person_click,0,1,4768.000000,0-4,1.000000
4,20090314441803444,176953,person_click,0,1,1416.333374,0-4,1.000000
5,20090315081004164,341352,object_click,0,1,4078.428467,0-4,0.666667
6,20090315085850788,425423,person_click,1,1,6231.222168,0-4,1.000000
7,20090315101457836,269374,person_click,1,1,2873.000000,0-4,1.000000
8,20090315170769824,272762,object_click,1,1,2510.000000,0-4,1.000000
9,20090317080721164,328805,object_click,1,1,2565.000000,0-4,0.333333
10,20090317111400710,825037,object_click,0,1,5987.083496,0-4,1.000000
11,20090317414400068,327643,person_click,1,1,1635.000000,0-4,1.000000
12,20090318322359292,391693,object_click,1,1,2277.428467,0-4,1.000000
13,20090318541618010,316571,person_click,1,1,1803.099976,0-4,1.000000
14,20090319012741024,373434,object_click,1,1,3867.000000,0-4,0.333333
15,20090320140443148,496142,object_click,0,1,1474.900024,0-4,0.333333
16,20100007011166932,340625,person_click,0,1,3916.909180,0-4,1.000000
17,20100008103581056,549450,person_click,1,1,7035.000000,0-4,1.000000
18,20100008262217530,272752,person_click,0,1,1823.000000,0-4,1.000000
19,20100009314461780,273757,person_click,1,1,1934.750000,0-4,1.000000
20,20100009560590796,313225,object_click,1,1,3461.928467,0-4,0.666667
21,20100010554738616,371043,person_click,1,0,4347.000000,0-4,0.666667
22,20100011033647636,313898,person_click,1,1,2575.000000,0-4,1.000000
23,20100011274731204,159833,person_click,1,1,1515.142822,0-4,0.666667
24,20100011290663880,312663,person_click,1,1,3345.666748,0-4,0.666667
25,20100011394713344,233145,person_click,1,1,3789.000000,0-4,1.000000
26,20100011571871700,284160,person_click,0,1,3811.625000,0-4,1.000000
27,20100012014517956,218380,person_click,0,0,2411.166748,0-4,1.000000
28,20100012363755750,334453,person_click,0,1,2378.500000,0-4,1.000000
29,20100012492111156,389006,person_click,0,1,5479.125000,0-4,0.666667
30,20100012540000424,1366231,person_click,0,1,3454.750000,0-4,1.000000
31,20100012562027690,153859,person_click,1,0,1617.599976,0-4,0.666667
32,20100013473331852,512748,person_click,1,1,4394.545410,0-4,1.000000
33,20100013511751244,195877,person_click,1,1,1999.000000,0-4,1.000000
34,20100014024611770,324466,person_click,1,1,2320.199951,0-4,1.000000
35,20100014035994700,328258,object_click,1,1,4310.399902,0-4,1.000000
36,20100015040218188,192572,person_click,0,1,1888.599976,0-4,1.000000
37,20100015283382064,342885,person_click,1,1,3073.699951,0-4,1.000000
38,20100015580955656,384558,person_click,1,1,2579.600098,0-4,1.000000
39,20100016070249504,181445,person_click,0,1,2476.666748,0-4,1.000000
40,20100016190952620,398634,person_click,0,1,7563.000000,0-4,0.666667
41,20100017041691464,267991,person_click,1,1,4635.000000,0-4,1.000000
42,20100017174504320,459427,person_click,1,1,4723.333496,0-4,0.666667
43,20100017254481760,397599,object_click,1,1,NaN,0-4,0.666667
44,20100017263056424,256766,person_click,1,1,3943.500000,0-4,1.000000
45,20100017310338576,2927934,person_click,1,1,2388.000000,0-4,1.000000
46,20100018303409816,43707118,person_click,0,1,4459.856934,0-4,1.000000
47,20100018421509572,302762,person_click,0,1,2039.166626,0-4,0.666667
48,20100020201084828,346523,object_click,1,0,4781.777832,0-4,0.666667
49,20100023124078624,239970,person_click,1,0,2170.166748,0-4,0.666667
50,20100106475056520,300334,person_click,1,1,1973.199951,0-4,0.666667
51,20100107064152736,171703,person_click,0,1,1612.111084,0-4,1.000000
52,20100107145631690,432488,object_click,1,1,2553.571533,0-4,1.000000
53,20100107482652664,320937,object_click,0,1,1586.076904,0-4,1.000000
54,20100107574055690,184433,person_click,0,1,2165.444336,0-4,1.000000
55,20100108361406030,258093,person_click,1,1,1382.599976,0-4,1.000000
56,20100108383025864,220278,person_click,0,1,1818.000000,0-4,1.000000
57,20100108432199556,1756062,person_click,0,1,2541.250000,0-4,1.000000
58,20100108444190744,379093,object_click,1,1,4996.899902,0-4,1.000000
59,20100108495321150,200003,person_click,1,1,1388.285767,0-4,1.000000

##### Section 2

In [77]:
data2 = test[test['level_group'] == '5-12']
data2

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
165,20090312431273200,175,221485,navigate_click,undefined,5,NaN,280.442169,-19.705837,653.0,321.0,NaN,NaN,boss,tunic.capitol_0.hall,NaN,5-12
166,20090312431273200,176,222334,person_click,basic,5,NaN,272.983490,-19.233582,649.0,321.0,NaN,"What are you still doing here, Jolie?",boss,tunic.capitol_0.hall,tunic.capitol_0.hall.boss.talktogramps,5-12
167,20090312431273200,177,223251,person_click,basic,5,NaN,240.848419,-228.217453,628.0,459.0,NaN,Go find your grampa and get to work!,boss,tunic.capitol_0.hall,tunic.capitol_0.hall.boss.talktogramps,5-12
168,20090312431273200,178,223735,navigate_click,undefined,5,NaN,331.714691,-220.627228,688.0,454.0,NaN,NaN,NaN,tunic.capitol_0.hall,NaN,5-12
169,20090312431273200,179,224235,navigate_click,undefined,5,NaN,404.147217,-226.491394,716.0,454.0,NaN,NaN,NaN,tunic.capitol_0.hall,NaN,5-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13173446,22100221145014656,795,3664936,navigate_click,undefined,12,NaN,939.575623,92.873199,805.0,268.0,NaN,NaN,tomap,tunic.historicalsociety.entry,NaN,5-12
13173447,22100221145014656,796,3665912,map_hover,basic,12,NaN,NaN,NaN,NaN,NaN,600.0,NaN,tomap,tunic.historicalsociety.entry,NaN,5-12
13173448,22100221145014656,797,3666188,map_click,undefined,12,NaN,486.913300,50.747986,465.0,298.0,NaN,NaN,tunic.capitol_1,tunic.historicalsociety.entry,NaN,5-12
13173449,22100221145014656,798,3667021,navigate_click,undefined,12,NaN,210.553955,-140.571701,395.0,390.0,NaN,NaN,chap2_finale_c,tunic.capitol_1.hall,NaN,5-12
13173450,22100221145014656,799,3668994,checkpoint,basic,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap2_finale_c,tunic.capitol_1.hall,NaN,5-12

In [88]:
# factor 1
total_elapsed_time = data2.groupby(['session_id'])['elapsed_time'].tail(1).reset_index()

# factor 2
filtered_data = data2[(data2['event_name'] != 'navigate_click') & (data2['event_name'] != 'cutscene_click')]
mode_event_name = filtered_data.groupby(['session_id'])['event_name'].apply(lambda x: x.mode()[0]).reset_index()

# factor 3
avg_page = data2.groupby(['session_id'])['page'].max().notnull().astype(int).reset_index()
avg_page = avg_page.rename(columns={'page': 'avg_page'})

# factor 4

# Find the maximum values of room_coor_x, screen_coor_x, room_coor_y, and screen_coor_y for each unique session_id
max_values = data2.groupby('session_id')[['room_coor_x', 'screen_coor_x', 'room_coor_y', 'screen_coor_y']].max()

# Create a new column named 'fullscreen' in the max_values dataframe that checks if the maximum room_coor_x is equal to the maximum screen_coor_x
max_values['fullscreen'] = (max_values['room_coor_x'] > 880) | (max_values['room_coor_y'] > 660)

# Create a new dataframe named 'fullscreen_df' that only contains the session_id and fullscreen columns from the max_values dataframe
fullscreen_df = max_values['fullscreen'].astype(int).reset_index()

# Merge the 'fullscreen' column with the unique 'session_id' column using an outer join on the 'session_id' column
unique_session_ids = data2['session_id'].unique()
unique_session_ids_df = pd.DataFrame({'session_id': unique_session_ids})
unique_session_ids_fullscreen = pd.merge(unique_session_ids_df, fullscreen_df, on='session_id', how='outer')

# Rename the 'fullscreen' column to 'fullscreen_flag'
unique_session_ids_fullscreen = unique_session_ids_fullscreen.rename(columns={'fullscreen': 'fullscreen_flag'})



# factor 5
avg_hover_duration = data2.groupby(['session_id'])['hover_duration'].mean().reset_index()

# Merge
temp_level_group = pd.DataFrame({'level_group': ['5-12'] * 11779})
part2 = pd.concat([avg_hover_duration['session_id'], 
                   total_elapsed_time['elapsed_time'], 
                   mode_event_name['event_name'], avg_page['avg_page'],
                     unique_session_ids_fullscreen['fullscreen_flag'],
                       avg_hover_duration['hover_duration'], 
                         temp_level_group['level_group'], sub1['correct']]
                          , axis = 1)


part2.head(60)

,session_id,elapsed_time,event_name,avg_page,fullscreen_flag,hover_duration,level_group,correct
0,20090312431273200,499235,person_click,0,1,969.333313,5-12,1.000000
1,20090312433251036,817609,person_click,1,1,824.096802,5-12,0.666667
2,20090314121766812,1017051,person_click,1,1,1641.134644,5-12,1.000000
3,20090314363702160,552723,person_click,0,1,1299.599976,5-12,1.000000
4,20090314441803444,550531,person_click,0,1,1459.235352,5-12,1.000000
5,20090315081004164,1409898,person_click,1,1,826.975586,5-12,0.666667
6,20090315085850788,1135963,person_click,1,1,2097.666748,5-12,1.000000
7,20090315101457836,743638,person_click,1,1,727.140381,5-12,1.000000
8,20090315170769824,775821,person_click,1,1,3105.550049,5-12,1.000000
9,20090317080721164,1273208,object_click,1,1,1973.827637,5-12,0.333333
10,20090317111400710,3472382,person_click,1,1,1488.170776,5-12,1.000000
11,20090317414400068,1053401,person_click,1,1,2504.586182,5-12,1.000000
12,20090318322359292,4797963,person_click,1,1,2407.047607,5-12,1.000000
13,20090318541618010,1017579,person_click,1,1,1488.871826,5-12,1.000000
14,20090319012741024,1029622,person_click,1,1,1183.694946,5-12,0.333333
15,20090320140443148,1414494,person_click,0,1,1355.365356,5-12,0.333333
16,20100007011166932,911170,person_click,0,1,1107.660400,5-12,1.000000
17,20100008103581056,2029593,person_click,1,1,3388.321533,5-12,1.000000
18,20100008262217530,757472,person_click,0,1,2001.214233,5-12,1.000000
19,20100009314461780,19850686,person_click,1,1,1040.333374,5-12,1.000000
20,20100009560590796,859192,person_click,1,1,1217.316650,5-12,0.666667
21,20100010554738616,1052059,person_click,1,1,2698.439941,5-12,0.666667
22,20100011033647636,832325,person_click,1,1,2608.111084,5-12,1.000000
23,20100011274731204,680752,object_click,1,1,1613.720947,5-12,0.666667
24,20100011290663880,909957,person_click,1,0,2439.695557,5-12,0.666667
25,20100011394713344,633790,person_click,1,1,1051.538452,5-12,1.000000
26,20100011571871700,852667,person_click,1,0,3831.944336,5-12,1.000000
27,20100012014517956,642510,person_click,1,1,1759.484863,5-12,1.000000
28,20100012363755750,849710,person_click,0,1,1130.527832,5-12,1.000000
29,20100012492111156,1725233,person_click,1,1,1635.085083,5-12,0.666667
30,20100012540000424,6357776,person_click,0,1,1801.468140,5-12,1.000000
31,20100012562027690,122696693,person_click,1,1,1226.846191,5-12,0.666667
32,20100013473331852,1720944,person_click,1,1,2374.410645,5-12,1.000000
33,20100013511751244,783559,person_click,1,1,1944.794067,5-12,1.000000
34,20100014024611770,775468,person_click,1,1,3896.785645,5-12,1.000000
35,20100014035994700,864374,person_click,0,1,1723.147095,5-12,1.000000
36,20100015040218188,558320,person_click,0,0,1186.862061,5-12,1.000000
37,20100015283382064,828212,person_click,1,1,2202.000000,5-12,1.000000
38,20100015580955656,1352973,person_click,1,1,3070.636475,5-12,1.000000
39,20100016070249504,600466,person_click,0,0,1619.904785,5-12,1.000000
40,20100016190952620,942444,person_click,1,1,2773.105225,5-12,0.666667
41,20100017041691464,731684,person_click,1,0,2513.750000,5-12,1.000000
42,20100017174504320,4263306,person_click,1,1,2118.483887,5-12,0.666667
43,20100017254481760,1377454,person_click,0,1,NaN,5-12,0.666667
44,20100017263056424,751068,person_click,1,1,1256.521729,5-12,1.000000
45,20100017310338576,758698,person_click,1,1,1226.444458,5-12,1.000000
46,20100018303409816,44361529,person_click,0,1,1940.599976,5-12,1.000000
47,20100018421509572,3806099,person_click,0,0,1511.658569,5-12,0.666667
48,20100020201084828,928393,person_click,1,1,1510.560059,5-12,0.666667
49,20100023124078624,639824,person_click,1,1,1334.433350,5-12,0.666667
50,20100106475056520,838494,person_click,1,1,1908.560059,5-12,0.666667
51,20100107064152736,640833,person_click,0,1,1757.151489,5-12,1.000000
52,20100107145631690,1359622,object_click,1,1,1181.245239,5-12,1.000000
53,20100107482652664,927946,person_click,0,1,1313.674438,5-12,1.000000
54,20100107574055690,648813,person_click,0,1,1073.586914,5-12,1.000000
55,20100108361406030,1547106,person_click,1,1,986.952393,5-12,1.000000
56,20100108383025864,721021,person_click,1,1,2096.769287,5-12,1.000000
57,20100108432199556,2596433,person_click,1,1,1871.000000,5-12,1.000000
58,20100108444190744,2049803,object_click,1,1,1233.471802,5-12,1.000000
59,20100108495321150,562380,person_click,0,1,2436.227295,5-12,1.000000

##### Section 3

In [84]:
data3 = test[test['level_group'] == '13-22']
data3

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
461,20090312431273200,512,836732,navigate_click,undefined,13,NaN,290.153564,-204.499359,651.0,445.0,NaN,NaN,NaN,tunic.capitol_1.hall,NaN,13-22
462,20090312431273200,513,837245,navigate_click,undefined,13,NaN,353.805603,-210.332062,672.0,445.0,NaN,NaN,NaN,tunic.capitol_1.hall,NaN,13-22
463,20090312431273200,514,837779,navigate_click,undefined,13,NaN,587.680054,-280.706238,780.0,489.0,NaN,NaN,NaN,tunic.capitol_1.hall,NaN,13-22
464,20090312431273200,515,838446,navigate_click,undefined,13,NaN,751.496887,-102.153290,823.0,365.0,NaN,NaN,toentry,tunic.capitol_1.hall,NaN,13-22
465,20090312431273200,516,839629,map_hover,basic,13,NaN,NaN,NaN,NaN,NaN,67.0,NaN,tunic.drycleaner,tunic.capitol_1.hall,NaN,13-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174206,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887299,36.701027,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
13174207,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696075,141.493179,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
13174208,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912872,140.569199,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
13174209,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299652,123.805893,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
13174210,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22

In [89]:
# factor 1
total_elapsed_time = data3.groupby(['session_id'])['elapsed_time'].tail(1).reset_index()

# factor 2
filtered_data = data3[(data3['event_name'] != 'navigate_click') & (data3['event_name'] != 'cutscene_click')]
mode_event_name = filtered_data.groupby(['session_id'])['event_name'].apply(lambda x: x.mode()[0]).reset_index()

# factor 3
avg_page = data3.groupby(['session_id'])['page'].max().notnull().astype(int).reset_index()
avg_page = avg_page.rename(columns={'page': 'avg_page'})

# factor 4

# Find the maximum values of room_coor_x, screen_coor_x, room_coor_y, and screen_coor_y for each unique session_id
max_values = data3.groupby('session_id')[['room_coor_x', 'screen_coor_x', 'room_coor_y', 'screen_coor_y']].max()

# Create a new column named 'fullscreen' in the max_values dataframe that checks if the maximum room_coor_x is equal to the maximum screen_coor_x
max_values['fullscreen'] = (max_values['room_coor_x'] > 880) | (max_values['room_coor_y'] > 660)

# Create a new dataframe named 'fullscreen_df' that only contains the session_id and fullscreen columns from the max_values dataframe
fullscreen_df = max_values['fullscreen'].astype(int).reset_index()

# Merge the 'fullscreen' column with the unique 'session_id' column using an outer join on the 'session_id' column
unique_session_ids = data3['session_id'].unique()
unique_session_ids_df = pd.DataFrame({'session_id': unique_session_ids})
unique_session_ids_fullscreen = pd.merge(unique_session_ids_df, fullscreen_df, on='session_id', how='outer')

# Rename the 'fullscreen' column to 'fullscreen_flag'
unique_session_ids_fullscreen = unique_session_ids_fullscreen.rename(columns={'fullscreen': 'fullscreen_flag'})



# factor 5
avg_hover_duration = data3.groupby(['session_id'])['hover_duration'].mean().reset_index()

# Merge
temp_level_group = pd.DataFrame({'level_group': ['13-22'] * 11779})
part3 = pd.concat([avg_hover_duration['session_id'], 
                   total_elapsed_time['elapsed_time'], 
                   mode_event_name['event_name'], avg_page['avg_page'],
                     unique_session_ids_fullscreen['fullscreen_flag'],
                       avg_hover_duration['hover_duration'], 
                         temp_level_group['level_group'], sub1['correct']]
                          , axis = 1)


part3.head(60)

,session_id,elapsed_time,event_name,avg_page,fullscreen_flag,hover_duration,level_group,correct
0,20090312431273200,1272679,person_click,0,1,899.925903,13-22,1.000000
1,20090312433251036,3815334,map_hover,1,1,720.384949,13-22,0.666667
2,20090314121766812,2133782,person_click,1,1,1013.456116,13-22,1.000000
3,20090314363702160,4208427,person_click,1,1,891.983032,13-22,1.000000
4,20090314441803444,1275750,person_click,0,1,982.425537,13-22,1.000000
5,20090315081004164,2974641,person_click,0,1,635.181824,13-22,0.666667
6,20090315085850788,2554792,person_click,1,1,2400.743652,13-22,1.000000
7,20090315101457836,1569636,person_click,1,1,835.016418,13-22,1.000000
8,20090315170769824,1578026,person_click,1,1,1525.551758,13-22,1.000000
9,20090317080721164,2491640,person_click,1,1,1856.078979,13-22,0.333333
10,20090317111400710,5462736,person_click,1,1,1129.651489,13-22,1.000000
11,20090317414400068,2002220,person_click,1,1,1381.689697,13-22,1.000000
12,20090318322359292,5660440,person_click,1,1,1701.400024,13-22,1.000000
13,20090318541618010,2343460,person_click,1,1,672.305115,13-22,1.000000
14,20090319012741024,2158678,person_click,1,1,1200.315796,13-22,0.333333
15,20090320140443148,38081617,person_click,0,1,1103.767700,13-22,0.333333
16,20100007011166932,1893408,person_click,0,1,717.516113,13-22,1.000000
17,20100008103581056,3722093,person_click,1,1,1743.918945,13-22,1.000000
18,20100008262217530,1882926,person_click,1,1,2750.722168,13-22,1.000000
19,20100009314461780,22056639,person_click,1,1,1057.054077,13-22,1.000000
20,20100009560590796,1808100,person_click,1,1,951.317078,13-22,0.666667
21,20100010554738616,2113002,person_click,1,1,1118.800049,13-22,0.666667
22,20100011033647636,2122128,person_click,1,1,1045.774658,13-22,1.000000
23,20100011274731204,2164739,person_click,1,1,519.661316,13-22,0.666667
24,20100011290663880,1907285,person_click,1,1,1107.314331,13-22,0.666667
25,20100011394713344,1409470,person_click,1,1,933.937500,13-22,1.000000
26,20100011571871700,2435273,person_click,0,1,1162.243286,13-22,1.000000
27,20100012014517956,1479036,person_click,0,1,1536.000000,13-22,1.000000
28,20100012363755750,1822463,person_click,0,1,865.333313,13-22,1.000000
29,20100012492111156,3572061,person_click,1,1,1335.047607,13-22,0.666667
30,20100012540000424,10459843,person_click,1,1,1723.285767,13-22,1.000000
31,20100012562027690,123549670,person_click,1,1,667.904785,13-22,0.666667
32,20100013473331852,3847165,person_click,1,1,1725.816284,13-22,1.000000
33,20100013511751244,1656960,person_click,1,1,1365.551758,13-22,1.000000
34,20100014024611770,1565826,person_click,1,1,2300.764648,13-22,1.000000
35,20100014035994700,1824749,person_click,0,1,1092.611084,13-22,1.000000
36,20100015040218188,1125726,person_click,0,1,923.857117,13-22,1.000000
37,20100015283382064,1648375,person_click,1,1,811.078918,13-22,1.000000
38,20100015580955656,2819923,person_click,1,1,1083.613647,13-22,1.000000
39,20100016070249504,1694808,person_click,1,1,737.535706,13-22,1.000000
40,20100016190952620,2082858,person_click,1,1,1384.119019,13-22,0.666667
41,20100017041691464,1500264,person_click,1,1,1789.461548,13-22,1.000000
42,20100017174504320,5768680,person_click,1,1,1088.033325,13-22,0.666667
43,20100017254481760,2558975,person_click,0,1,NaN,13-22,0.666667
44,20100017263056424,1780823,person_click,1,1,748.812500,13-22,1.000000
45,20100017310338576,2526620,person_click,1,1,1353.421021,13-22,1.000000
46,20100018303409816,49966056,person_click,1,1,900.185730,13-22,1.000000
47,20100018421509572,5494900,person_click,1,1,5117.333496,13-22,0.666667
48,20100020201084828,2015152,person_click,1,1,724.901611,13-22,0.666667
49,20100023124078624,1469909,person_click,1,1,787.404236,13-22,0.666667
50,20100106475056520,1700163,person_click,1,1,892.361084,13-22,0.666667
51,20100107064152736,1813837,person_click,0,1,1084.312500,13-22,1.000000
52,20100107145631690,2657782,person_click,1,1,822.176453,13-22,1.000000
53,20100107482652664,1897221,person_click,0,1,1301.847412,13-22,1.000000
54,20100107574055690,1912954,person_click,1,1,766.280884,13-22,1.000000
55,20100108361406030,4698440,person_click,1,1,920.888916,13-22,1.000000
56,20100108383025864,2609786,person_click,1,1,808.450989,13-22,1.000000
57,20100108432199556,5417755,person_click,1,1,1458.485718,13-22,1.000000
58,20100108444190744,3686479,person_click,1,1,1231.313477,13-22,1.000000
59,20100108495321150,1398320,person_click,1,1,1404.260864,13-22,1.000000

### 4.3 Final Step for combining dataset together

In [90]:
new_data = pd.concat([part1, part2, part3], axis = 0)
new_data

,session_id,elapsed_time,event_name,avg_page,fullscreen_flag,hover_duration,level_group,correct
0,20090312431273200,194860,person_click,0,1,2.389500e+03,0-4,1.000000
1,20090312433251036,233752,person_click,1,1,1.378750e+03,0-4,0.666667
2,20090314121766812,393360,object_click,1,1,1.603400e+03,0-4,1.000000
3,20090314363702160,217574,person_click,0,1,4.768000e+03,0-4,1.000000
4,20090314441803444,176953,person_click,0,1,1.416333e+03,0-4,1.000000
...,...,...,...,...,...,...,...,...
11774,22100215342220508,57742000,person_click,1,1,1.465038e+06,13-22,1.000000
11775,22100215460321130,2104501,person_click,1,1,7.803636e+02,13-22,0.666667
11776,22100217104993650,2103885,person_click,1,1,1.072135e+03,13-22,1.000000
11777,22100219442786200,1218877,person_click,1,1,1.110500e+03,13-22,0.666667
11778,22100221145014656,5487952,person_click,1,1,6.690000e+02,13-22,0.333333

In [94]:
new_data = new_data.sort_values(['session_id', 'level_group'], ascending=[True, True])
new_data.head(50)

,session_id,elapsed_time,event_name,avg_page,fullscreen_flag,hover_duration,level_group,correct
0,20090312431273200,194860,person_click,0,1,2389.500000,0-4,1.000000
0,20090312431273200,1272679,person_click,0,1,899.925903,13-22,1.000000
0,20090312431273200,499235,person_click,0,1,969.333313,5-12,1.000000
1,20090312433251036,233752,person_click,1,1,1378.750000,0-4,0.666667
1,20090312433251036,3815334,map_hover,1,1,720.384949,13-22,0.666667
1,20090312433251036,817609,person_click,1,1,824.096802,5-12,0.666667
2,20090314121766812,393360,object_click,1,1,1603.400024,0-4,1.000000
2,20090314121766812,2133782,person_click,1,1,1013.456116,13-22,1.000000
2,20090314121766812,1017051,person_click,1,1,1641.134644,5-12,1.000000
3,20090314363702160,217574,person_click,0,1,4768.000000,0-4,1.000000
3,20090314363702160,4208427,person_click,1,1,891.983032,13-22,1.000000
3,20090314363702160,552723,person_click,0,1,1299.599976,5-12,1.000000
4,20090314441803444,176953,person_click,0,1,1416.333374,0-4,1.000000
4,20090314441803444,1275750,person_click,0,1,982.425537,13-22,1.000000
4,20090314441803444,550531,person_click,0,1,1459.235352,5-12,1.000000
5,20090315081004164,341352,object_click,0,1,4078.428467,0-4,0.666667
5,20090315081004164,2974641,person_click,0,1,635.181824,13-22,0.666667
5,20090315081004164,1409898,person_click,1,1,826.975586,5-12,0.666667
6,20090315085850788,425423,person_click,1,1,6231.222168,0-4,1.000000
6,20090315085850788,2554792,person_click,1,1,2400.743652,13-22,1.000000
6,20090315085850788,1135963,person_click,1,1,2097.666748,5-12,1.000000
7,20090315101457836,269374,person_click,1,1,2873.000000,0-4,1.000000
7,20090315101457836,1569636,person_click,1,1,835.016418,13-22,1.000000
7,20090315101457836,743638,person_click,1,1,727.140381,5-12,1.000000
8,20090315170769824,272762,object_click,1,1,2510.000000,0-4,1.000000
8,20090315170769824,1578026,person_click,1,1,1525.551758,13-22,1.000000
8,20090315170769824,775821,person_click,1,1,3105.550049,5-12,1.000000
9,20090317080721164,328805,object_click,1,1,2565.000000,0-4,0.333333
9,20090317080721164,2491640,person_click,1,1,1856.078979,13-22,0.333333
9,20090317080721164,1273208,object_click,1,1,1973.827637,5-12,0.333333
10,20090317111400710,825037,object_click,0,1,5987.083496,0-4,1.000000
10,20090317111400710,5462736,person_click,1,1,1129.651489,13-22,1.000000
10,20090317111400710,3472382,person_click,1,1,1488.170776,5-12,1.000000
11,20090317414400068,327643,person_click,1,1,1635.000000,0-4,1.000000
11,20090317414400068,2002220,person_click,1,1,1381.689697,13-22,1.000000
11,20090317414400068,1053401,person_click,1,1,2504.586182,5-12,1.000000
12,20090318322359292,391693,object_click,1,1,2277.428467,0-4,1.000000
12,20090318322359292,5660440,person_click,1,1,1701.400024,13-22,1.000000
12,20090318322359292,4797963,person_click,1,1,2407.047607,5-12,1.000000
13,20090318541618010,316571,person_click,1,1,1803.099976,0-4,1.000000
13,20090318541618010,2343460,person_click,1,1,672.305115,13-22,1.000000
13,20090318541618010,1017579,person_click,1,1,1488.871826,5-12,1.000000
14,20090319012741024,373434,object_click,1,1,3867.000000,0-4,0.333333
14,20090319012741024,2158678,person_click,1,1,1200.315796,13-22,0.333333
14,20090319012741024,1029622,person_click,1,1,1183.694946,5-12,0.333333
15,20090320140443148,496142,object_click,0,1,1474.900024,0-4,0.333333
15,20090320140443148,38081617,person_click,0,1,1103.767700,13-22,0.333333
15,20090320140443148,1414494,person_click,0,1,1355.365356,5-12,0.333333
16,20100007011166932,340625,person_click,0,1,3916.909180,0-4,1.000000
16,20100007011166932,1893408,person_click,0,1,717.516113,13-22,1.000000

### As shown above, for each player we divide the whole process into 3 stages according to level group, and for each stage we extract characteristic data and form 5 total columns that related to performance. This wrap up our preprocessing and can start EDA.

# EDA