# Preprocessing train data

In [5]:
import numpy as np 
import pandas as pd

In [6]:
data = pd.read_csv("train.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 20 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int64
 2   elapsed_time    int64
 3   event_name      object
 4   name            object
 5   level           int64
 6   page            float64
 7   room_coor_x     float64
 8   room_coor_y     float64
 9   screen_coor_x   float64
 10  screen_coor_y   float64
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  fullscreen      float64
 17  hq              float64
 18  music           float64
 19  level_group     object
dtypes: float64(9), int64(4), object(7)
memory usage: 2.0+ GB

## 1. Have an Overview of data

In [15]:
data.describe(include='all')

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
count,1.317421e+07,1.317421e+07,1.317421e+07,13174211,13174211,1.317421e+07,284746.000000,1.213797e+07,1.213797e+07,1.213797e+07,1.213797e+07,1.000737e+06,4806891,9014563,13174211,4806945,0.0,0.0,0.0,13174211
unique,NaN,NaN,NaN,11,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594,127,19,126,NaN,NaN,NaN,3
top,NaN,NaN,NaN,navigate_click,undefined,NaN,NaN,NaN,NaN,NaN,NaN,NaN,undefined,worker,tunic.historicalsociety.entry,tunic.historicalsociety.cage.confrontation,NaN,NaN,NaN,13-22
freq,NaN,NaN,NaN,5687896,6377305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178294,939555,1816202,333363,NaN,NaN,NaN,6746397
mean,2.113413e+16,6.526426e+02,3.846817e+06,NaN,NaN,1.219194e+01,3.157930,-5.493615e+01,-1.162997e+02,4.581144e+02,3.852363e+02,3.186237e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5.665220e+14,6.275818e+02,2.701387e+07,NaN,NaN,6.499188e+00,2.064042,5.201468e+02,2.185912e+02,2.472144e+02,1.292879e+02,3.692265e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.009031e+16,0.000000e+00,0.000000e+00,NaN,NaN,0.000000e+00,0.000000,-1.992355e+03,-9.181587e+02,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2.101031e+16,2.890000e+02,4.394300e+05,NaN,NaN,6.000000e+00,1.000000,-3.529376e+02,-2.128361e+02,2.690000e+02,3.040000e+02,1.000000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.104022e+16,5.960000e+02,1.013425e+06,NaN,NaN,1.300000e+01,3.000000,-1.116317e+01,-9.778151e+01,4.470000e+02,3.970000e+02,4.180000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.110051e+16,8.970000e+02,1.740050e+06,NaN,NaN,1.800000e+01,5.000000,2.963618e+02,2.268531e+01,6.630000e+02,4.710000e+02,1.266000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.210022e+16,2.047300e+04,1.749293e+09,NaN,NaN,2.200000e+01,6.000000,1.261774e+03,5.436164e+02,1.916000e+03,1.439000e+03,2.199078e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
print(data.head(100))

           session_id  index  elapsed_time      event_name       name  level  \
0   20090312431273200      0             0  cutscene_click      basic      0
1   20090312431273200      1          1323    person_click      basic      0
2   20090312431273200      2           831    person_click      basic      0
3   20090312431273200      3          1147    person_click      basic      0
4   20090312431273200      4          1863    person_click      basic      0
..                ...    ...           ...             ...        ...    ...
95  20090312431273200     95         98859    person_click      basic      2
96  20090312431273200     96         99459    person_click      basic      2
97  20090312431273200     97         99958    person_click      basic      2
98  20090312431273200     98        100713    person_click      basic      2
99  20090312431273200     99        101042  navigate_click  undefined      3

    page  room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  \
0    NaN  -413.991405  -159.314686          380.0          494.0
1    NaN  -413.991405  -159.314686          380.0          494.0
2    NaN  -413.991405  -159.314686          380.0          494.0
3    NaN  -413.991405  -159.314686          380.0          494.0
4    NaN  -412.991405  -159.314686          381.0          494.0
..   ...          ...          ...            ...            ...
95   NaN   277.753433  -166.585120          613.0          444.0
96   NaN   368.432843  -176.661681          676.0          451.0
97   NaN   368.432120  -176.661922          676.0          451.0
98   NaN   400.098469  -176.662028          698.0          451.0
99   NaN   400.098371  -175.222667          698.0          450.0

    hover_duration                                               text    fqid  \
0              NaN                                          undefined   intro
1              NaN                      Whatcha doing over there, Jo?  gramps
2              NaN                             Just talking to Teddy.  gramps
3              NaN                         I gotta run to my meeting!  gramps
4              NaN                                Can I come, Gramps?  gramps
..             ...                                                ...     ...
95             NaN                    Could be. But we need evidence!  gramps
96             NaN  Why don't you head to the Basketball Center an...  gramps
97             NaN                                              Sure!  gramps
98             NaN  I'll be at the Capitol. Let me know if you fin...  gramps
99             NaN                                                NaN     NaN

                             room_fqid  \
0       tunic.historicalsociety.closet
1       tunic.historicalsociety.closet
2       tunic.historicalsociety.closet
3       tunic.historicalsociety.closet
4       tunic.historicalsociety.closet
..                                 ...
95  tunic.historicalsociety.collection
96  tunic.historicalsociety.collection
97  tunic.historicalsociety.collection
98  tunic.historicalsociety.collection
99  tunic.historicalsociety.collection

                                            text_fqid  fullscreen  hq  music  \
0                tunic.historicalsociety.closet.intro         NaN NaN    NaN
1   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
2   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
3   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
4   tunic.historicalsociety.closet.gramps.intro_0_...         NaN NaN    NaN
..                                                ...         ...  ..    ...
95    tunic.historicalsociety.collection.gramps.found         NaN NaN    NaN
96    tunic.historicalsociety.collection.gramps.found         NaN NaN    NaN
97    tunic.historicalsociety.collection.gramps.found         NaN NaN    NaN
98    tunic.historicalsociety.collection.gramps.found         NaN NaN    NaN
99                                                NaN         NaN NaN    NaN

   level_group
0          0-4
1          0-4
2          0-4
3          0-4
4          0-4
..         ...
95         0-4
96         0-4
97         0-4
98         0-4
99         0-4

[100 rows x 20 columns]

## 2. Wipe out NA values

In [22]:
## drop those columns as NA
data = data.drop(['music','hq','fullscreen'], axis=1)
print(data.head())

          session_id  index  elapsed_time      event_name   name  level  page  \
0  20090312431273200      0             0  cutscene_click  basic      0   NaN
1  20090312431273200      1          1323    person_click  basic      0   NaN
2  20090312431273200      2           831    person_click  basic      0   NaN
3  20090312431273200      3          1147    person_click  basic      0   NaN
4  20090312431273200      4          1863    person_click  basic      0   NaN

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405  -159.314686          380.0          494.0             NaN
1  -413.991405  -159.314686          380.0          494.0             NaN
2  -413.991405  -159.314686          380.0          494.0             NaN
3  -413.991405  -159.314686          380.0          494.0             NaN
4  -412.991405  -159.314686          381.0          494.0             NaN

                            text    fqid                       room_fqid  \
0                      undefined   intro  tunic.historicalsociety.closet
1  Whatcha doing over there, Jo?  gramps  tunic.historicalsociety.closet
2         Just talking to Teddy.  gramps  tunic.historicalsociety.closet
3     I gotta run to my meeting!  gramps  tunic.historicalsociety.closet
4            Can I come, Gramps?  gramps  tunic.historicalsociety.closet

                                           text_fqid level_group
0               tunic.historicalsociety.closet.intro         0-4
1  tunic.historicalsociety.closet.gramps.intro_0_...         0-4
2  tunic.historicalsociety.closet.gramps.intro_0_...         0-4
3  tunic.historicalsociety.closet.gramps.intro_0_...         0-4
4  tunic.historicalsociety.closet.gramps.intro_0_...         0-4

In [23]:
data['elapsed_time'] = data['elapsed_time'].astype(np.uint32)
data['level'] = data['level'].astype(np.uint8)
data['room_coor_x'] = data['room_coor_x'].astype(np.float32)
data['room_coor_y'] = data['room_coor_y'].astype(np.float32)
data['screen_coor_x'] = data['screen_coor_x'].astype(np.float32)
data['screen_coor_y'] = data['screen_coor_y'].astype(np.float32)
data['hover_duration'] = data['hover_duration'].astype(np.float32)


columns_to_convert = ['session_id','event_name','name','page','text','fqid','room_fqid','text_fqid','level_group']

for column in columns_to_convert:
    data[column] = data[column].astype('category')
    
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 17 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      category
 1   index           int64
 2   elapsed_time    uint32
 3   event_name      category
 4   name            category
 5   level           uint8
 6   page            category
 7   room_coor_x     float32
 8   room_coor_y     float32
 9   screen_coor_x   float32
 10  screen_coor_y   float32
 11  hover_duration  float32
 12  text            category
 13  fqid            category
 14  room_fqid       category
 15  text_fqid       category
 16  level_group     category
dtypes: category(9), float32(5), int64(1), uint32(1), uint8(1)
memory usage: 565.7 MB

## Great! Now we reduced 2.3 GB to 565 MB, saved around 77% memory space!

## 3. (Optional) Save data in new csv file. (ps: Now 2/3 of group member's laptop can finally open .csv file! )

In [25]:
data.to_csv('train2.csv', index=False)